### ISSUE TITLE
gevent monkey patching breaks celery workers in the strangest ways

### ISSUE THREAD

**Issue by hheimbuerger** [bonnierpolska/devourer#1]
I've been trying to use devourer 0.3.3 from celery workers (prefork pool) and they started breaking in the weirdest ways.

Depending on where I would import devourer, I would for example get this exception:

```
[2016-10-20 15:22:22,967] ERROR [-/-/-/celery.worker.job] Task myapp.mytask[a05031c7-3e16-4edb-b484-c51f6976d244] raised unexpected: DatabaseError("DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 4628 and this is thread id 55128752.",)
Traceback (most recent call last):
  File "c:\python\2.7\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\python\2.7\lib\site-packages\celery\app\trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "c:\code\src\myapp\tasks.py", line 96, in mytask
    query_models_here()
  File "c:\python\2.7\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\python\2.7\lib\site-packages\django\db\models\query.py", line 381, in get
    num = len(clone)
  File "c:\python\2.7\lib\site-packages\django\db\models\query.py", line 240, in __len__
    self._fetch_all()
  File "c:\python\2.7\lib\site-packages\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "c:\python\2.7\lib\site-packages\django\db\models\query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "c:\python\2.7\lib\site-packages\django\db\models\sql\compiler.py", line 846, in execute_sql
    cursor = self.connection.cursor()
  File "c:\python\2.7\lib\site-packages\django\db\backends\base\base.py", line 229, in cursor
    self.validate_thread_sharing()
  File "c:\python\2.7\lib\site-packages\django\db\backends\base\base.py", line 524, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident()))
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 4628 and this is thread id 55128752.
```

In other cases, all forked celery workers would freeze and no longer accept any tasks or even respond to termination signals.

Eventually, I could narrow this down to the gevent monkey patching in `devourer/api.py:12`:

```
import gevent
from gevent import monkey
monkey.patch_all()
```

Since I've taken these lines out (I'm not using gevent or devourer's async calls anywhere right now), celery behaves normally again.

**Comment by bujniewicz** [comment]
Hi, actually this is on the radar since it broke a bunch of my own stuff too, I have a solution in mind and hopefully will be able to implement it on Sunday. Whole async change was done by company owning this project, not by me, so I couldn't actually alter the changes to be backward-compatible before the release, but will do so ASAP.

And the actual issue is (for anyone wondering) - you shouldn't ever monkey.patch_all() in a library. It needs to be in an entry point, before anything else happens, or not at all..

**Comment by bujniewicz** [comment]
Devourer 0.4.0 fixes those issues and introduces real async support. @hheimbuerger can you confirm if it solves your problems as well?

**Comment by hheimbuerger** [comment]
@bujniewicz I've switched from my fork back to the official 0.4.2 release on PyPI, and a quick test showed no issues. Thanks!

I can confirm that this resolves my problems. I'll let you know if anything new comes up.

**Comment by bujniewicz** [comment]
Great, thanks!

**Comment by Abuba-oss** [comment]
@bujniewicz can you please explain the steps in solving the issue with Devourer 0.4.0?. I'm kinda confused after I pip install it in my project. would appreciate your support. thank you!

**Comment by bujniewicz** [comment]
Hi @Abuba-oss, I'm not sure what exact issue do you have. Do you mind elaborating?
